name: poc
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  go_router: ^16.2.4
  flutter_bloc: ^9.1.1
  camera: ^0.11.2
  path_provider: ^2.1.5
  equatable: ^2.0.7
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  video_thumbnail: ^0.5.6
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets pour les modèles ML et autres ressources
  assets:
    - assets/models/
    - assets/models/mobilenet_v2.tflite
    - assets/models/labels.txt
    - assets/models/pose_landmarker_lite.task
    - assets/models/pose_landmarker_full.task
    - assets/models/pose_landmarker_heavy.task
